### ISSUE TITLE
Mi infografía de RA

### ISSUE THREAD

**Issue by ThorSampy** [SistemasTecTlaxiaco/infografia-ThorSampy#1]
[Infografía Sammy.pdf](https://github.com/SistemasTecTlaxiaco/infografia-ThorSampy/files/8127163/Infografia.Sammy.pdf)

**Comment by Christopherg2** [comment]
Muy bien compañero tu trabajo esta completo, y cumple con todos los requisitos. 
20 puntos

**Comment by josealfredo79** [comment]
Muy hecho y revisado
