### ISSUE TITLE
INFOGRAFIA-REQUISITOS

### ISSUE THREAD

**Issue by ThorSampy** [SistemasTecTlaxiaco/infografia-ThorSampy#2]
![WhatsApp Image 2021-03-22 at 3 15 14 PM](https://user-images.githubusercontent.com/72049122/112392800-a59b6980-8cbf-11eb-9c23-4b28320ee941.jpeg)

**Comment by josealfredo79** [comment]
Bien hecho y revisado.

**Comment by DavidFeria01** [comment]
buen trabajo solo falto un poco mas de imagen

**Comment by DavidFeria01** [comment]
calificacion : 18%
